apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app}}
  namespace: {{.Values.namespace}}
spec:
  type: ClusterIP
  ports:
    - port: {{.Values.service.port}}
      name: http
  selector:
    app: {{.Values.app}}

